### ISSUE TITLE
When is the code open source?

### ISSUE THREAD

**Issue by RuoyuChen10** [ParthaEth/GIF#1]
Thanks to your work "GIF: Generative Interpretable Faces", and I'm interested in this work and desiring for the source code. I wonder when it will be public, or can you send the original code to me? Thanks, looking forward your reply.

**Comment by GuptaPravirSingh** [comment]
@RuoyuChen10 : We have released main parts of the code. We will shortly release the remaining parts too.

**Comment by ParthaEth** [comment]
Now a trainble version of the code is up. The pre-trained model and the training data will follow soon.

**Comment by ParthaEth** [comment]
Now all parts of the code is online. :-)
