### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by ZekuiQin** [ParthaEth/GIF#10]
when I run **python train.py --run_id 0**, an error appear:
<img width="1527" alt="截屏2020-12-30 下午8 30 29" src="https://user-images.githubusercontent.com/40821171/103351531-82a55300-4ade-11eb-9e67-f1e807aa23d8.png">

**Comment by ZekuiQin** [comment]
similarly, when I run **python plots/generate_random_samples.py**, got:
<img width="1542" alt="截屏2020-12-30 下午8 36 26" src="https://user-images.githubusercontent.com/40821171/103351682-ef205200-4ade-11eb-93b2-813eab86d488.png">

**Comment by visonpon** [comment]
@ZekuiQin,Just do as the error says, modify the view with reshape

**Comment by ZekuiQin** [comment]
it works, thanks!!!
