### ISSUE TITLE
output images are fine, but the meshes are all black

### ISSUE THREAD

**Issue by visonpon** [ParthaEth/GIF#12]
Hi @ParthaEth,thanks for your great work, and I have try to train on my own dataset based on your pretrained model. while the generated images look fine , but the saved meshes in the conditon dir are all black.

Hope you can give some advices, thanks~

**Comment by ParthaEth** [comment]
Did you check if you can render the meshes correctly? The model take rendered meshes as condition input. So even if you send in black images it will generate good looking images just that they will not have any condition association.

**Comment by visonpon** [comment]
I set the `run_id=29 `and after trained for a while I use the `generate_random_samples.py ` to generate some results.
 I notice that in the original dir `./outputs_files/smaple/29/random_samples_q_eval_full_model`, there also exist some mesh images that are black but the images are fine. So I think my train phase is normal.
I wonder how to set the flame parameters properly so that the saved mesh are normal and can see a direct corresponding sematic connection between the mesh and generated images. thanks~

**Comment by visonpon** [comment]
I came to notice that I can use deca to generate FLAME parameters, sorry for the bother, thanks~

**Comment by visonpon** [comment]
@ParthaEth, I have tried to use DECA to get FLAME parameters, but when using these parameters to generate an image, the saved mesh still all black.

Hope you can help, thanks~

**Comment by littlePrince126** [comment]
@visonpon Has this problem been solved? I have the same situation.

**Comment by arnobanu** [comment]
I am also facing the same problem.
