### ISSUE TITLE
done 

### ISSUE THREAD

**Issue by diaodeyi** [ParthaEth/GIF#15]

**Comment by ParthaEth** [comment]
Which package causes this problem? you can try to isolate it by commenting out the packages that you suspect are causing the trouble and then seeing if the error disappears. After that you can find why exactly that is the case

**Comment by diaodeyi** [comment]
pytorch3d&nbsp;





------------------ Original ------------------

**Comment by diaodeyi** [comment]
pytorch3d , and your requirement in it says pytorch1.4 or 1.5
