### ISSUE TITLE
train on my own datasets ,but the test results are bad

### ISSUE THREAD

**Issue by visonpon** [ParthaEth/GIF#18]
Hi, @ParthaEth, I have followed your step to create my own datasets, but after train for a few days, the test results are all bad(I only use one person(6k images) to train, and it contain abundant expression and pose )

![329292484](https://user-images.githubusercontent.com/11517731/105693371-9a83c180-5f3a-11eb-8ded-93c62d80c042.jpg)

I first use DECA to get parameters and then create the datasets use the scripts in prepare_lmdb
My loss values are nearly like below:  G_loss=5.x/ D_loss=1.x/embd_reg_loss=0/interp_loss=2.x 

Hope you can give some advice, thanks~

**Comment by ParthaEth** [comment]
If you had good FID during train, My best guess is that at test time your rendered meshes are not normalized properly, i.e. same as train time. Different normalization? Just put a debug point ans see the range of values.
