### ISSUE TITLE
Problem with run generate_random_samples.py

### ISSUE THREAD

**Issue by xiaoF981204** [ParthaEth/GIF#20]
Hi,@ParthaEth,when I run the generate_random_samples.py,it has some problems in /GIF-master/my_utils/photometric_optimization/renderer.py,could you please tell me how to solve it?Thank you very much!
![L34~F9HBS}CYNAT01{8A5 Y](https://user-images.githubusercontent.com/60803384/117456390-b60b5900-af7a-11eb-9e0e-98a65bc73616.png)

**Comment by ParthaEth** [comment]
Hi was the flame model unable to load texture map or something like that? Can you please trace-back the None? i.e. finding out why verts_uvs are None

**Comment by wjxzju** [comment]
@xiaoF981204 I also meet this problem, the resource file head_template_mesh.obj and b_box_stats.npz are  stored with git lfs, you need redownload these two files.

**Comment by ParthaEth** [comment]
Seems like its solved with wjxzju's solution
