### ISSUE TITLE
[Q]. How to get images of similar appearance but different pose face images like fig.1 in the paper?

### ISSUE THREAD

**Issue by univ-esuty** [ParthaEth/GIF#23]
I've tested `generate_sample_random.py`. The image quality is very nice but, the generated faces doesn't look like the same person.
Does anyone know what should we change the parts of code to generate images of similar appearances but different poses like fig.1 in the paper?

**Comment by ParthaEth** [comment]
you should only change the pose parameters of the flame code and hold the style vector and the rest of the parameters such as lighting and texture constant.
