### ISSUE TITLE
ModuleNotFoundError: No module named 'my_utils.photometric_optimization.models'

### ISSUE THREAD

**Issue by valsevalse** [ParthaEth/GIF#28]
Hi! I've followed the "First thing first" instructions. Now I'd like to generate some images, without any training, so I continued with the "To run random face generation" instructions, but I get this error

python role_of_different_parameters.py 
Traceback (most recent call last):
  File "role_of_different_parameters.py", line 7, in <module>
    from model.stg2_generator import StyledGenerator
  File "../model/stg2_generator.py", line 15, in <module>
    from my_utils.photometric_optimization.models import FLAME
ModuleNotFoundError: No module named 'my_utils.photometric_optimization.models'

**Comment by ParthaEth** [comment]
Seems like you somehow did not complete the step 2 and 3 of the 'first thing first todo'. Can you check if you have the checkpoints in the right place?

**Comment by valsevalse** [comment]
Yes, they are. 

GIF_resources/output_files/checkpoint/29/294000_1.model

and I have my constants.py set to

resources_root = '/home/valse/GIF/GIF_resources'

**Comment by ParthaEth** [comment]
Oh, my bad this is a python import error. photometric_optimization is a submodule from another repository that I use. you have to git clone with submodule recursion. Otherwise external libraries are not cloned `git clone --recurse-submodules <URL>`  for the future.

for now, do 
```
git submodule init
git submodule update
```

**Comment by valsevalse** [comment]
Thanks!
