### ISSUE TITLE
GIF_resources link is missing

### ISSUE THREAD

**Issue by OWLonoak** [ParthaEth/GIF#3]
Thinks for your great job, it's brings new ideas to this research topic.
However, I find that GIF_resources file is missing, and the link to the file is not public available.
Could you please release necessary files recently? Can't wait to run your code.

Thanks.

**Comment by ParthaEth** [comment]
We are working on it. Stay tuned. Hopefully it will be up before this week ends. :-)

**Comment by ParthaEth** [comment]
Please note that GIF training files and checkpoints are now available here -  http://files.is.tuebingen.mpg.de/gif/input_files.zip; http://files.is.tuebingen.mpg.de/gif/output_files.zip
