### ISSUE TITLE
File not found:'b_box_stats.npz'

### ISSUE THREAD

**Issue by dmdomo** [ParthaEth/GIF#5]
Thanks for your work.
When I run codes under "plots/voca/", I got an error: Can't find the file named "b_box_stats.npz", I found that the path of "b_box_stats.npz" is from "constants.py",line 50.
 I don’t know where to get this file. Could you tell me how to get it?

**Comment by ParthaEth** [comment]
Just pushed it as an LSF file. you can simply pull it.
