### ISSUE TITLE
File not found:'texture_data_FLAME_256.npy'

### ISSUE THREAD

**Issue by GIVEzju** [ParthaEth/GIF#8]
Thank for your work!
I can't find "texture_data_FLAME_256.npy"
I only have "FLAME_texture.npz". Does "texture_data_FLAME_256.npy" come from FLAME_texture.npz?

**Comment by ParthaEth** [comment]
Thanks for the bug report. The texture model of FLAME is available separately - here - https://github.com/TimoBolkart/TF_FLAME. I have modified the read me accordingly. Note also that I have renamed the file to be  - `texture_data_256.npy` as that is the default download name.

**Comment by yangqing-yq** [comment]
> FLAME_texture.npz

where to download "FLAME_texture.npz"?
